{"trial_id": "0002", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "embedding_dim", "default": null, "conditions": [], "min_value": 32, "max_value": 128, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "lstm_units", "default": null, "conditions": [], "min_value": 32, "max_value": 128, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "dense_units", "default": null, "conditions": [], "min_value": 32, "max_value": 128, "step": 32, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout", "default": 0.2, "conditions": [], "min_value": 0.2, "max_value": 0.5, "step": 0.1, "sampling": "linear"}}], "values": {"embedding_dim": 64, "lstm_units": 128, "dense_units": 96, "dropout": 0.30000000000000004, "tuner/epochs": 2, "tuner/initial_epoch": 0, "tuner/bracket": 2, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 53, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InternalError: Graph execution error:\n\nDetected at node sequential_1/bidirectional_1_2/forward_lstm_1_1/CudnnRNNV3 defined at (most recent call last):\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/main_v4.py\", line 73, in <module>\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/main_v4.py\", line 33, in run_tunner\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 234, in search\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 320, in fit\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 833, in __call__\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 889, in _call\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 696, in _initialize\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 178, in trace_function\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 283, in _maybe_define_function\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 310, in _create_concrete_function\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py\", line 1059, in func_graph_from_py_func\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 599, in wrapped_fn\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/autograph_util.py\", line 41, in autograph_handler\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 339, in converted_call\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 459, in _call_unconverted\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 121, in one_step_on_iterator\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 1673, in run\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 3263, in call_for_each_replica\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py\", line 4061, in _call_for_each_replica\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 833, in __call__\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 906, in _call\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 132, in call_function\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 178, in trace_function\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 283, in _maybe_define_function\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py\", line 310, in _create_concrete_function\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py\", line 1059, in func_graph_from_py_func\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 599, in wrapped_fn\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/autograph_util.py\", line 41, in autograph_handler\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 331, in converted_call\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 459, in _call_unconverted\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py\", line 643, in wrapper\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 108, in one_step_on_data\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 51, in train_step\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 899, in __call__\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/ops/operation.py\", line 46, in __call__\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/models/sequential.py\", line 213, in call\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/models/functional.py\", line 182, in call\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/ops/function.py\", line 171, in _run_through_graph\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/models/functional.py\", line 584, in call\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 899, in __call__\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/ops/operation.py\", line 46, in __call__\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/layers/rnn/bidirectional.py\", line 218, in call\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/layers/layer.py\", line 899, in __call__\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/ops/operation.py\", line 46, in __call__\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/layers/rnn/lstm.py\", line 570, in call\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/layers/rnn/rnn.py\", line 406, in call\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/layers/rnn/lstm.py\", line 537, in inner_loop\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/backend/tensorflow/rnn.py\", line 841, in lstm\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/keras/src/backend/tensorflow/rnn.py\", line 933, in _cudnn_lstm\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py\", line 377, in wrapper\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/ops/gen_cudnn_rnn_ops.py\", line 1964, in cudnn_rnnv3\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/framework/op_def_library.py\", line 796, in _apply_op_helper\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py\", line 670, in _create_op_internal\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 2701, in _create_op_internal\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1196, in from_node_def\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/framework/ops.py\", line 1062, in _create_c_op\n\n  File \"/home/nikolas/git/alura/keras/ClassificacaoSugestaoPalavras/.venv/lib/python3.10/site-packages/tensorflow/python/util/tf_stack.py\", line 162, in extract_stack\n\nFailed to call DoRnnForward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size, cell_num_units]: [1, 256, 128, 1, 133, 4096, 128] \n\t [[{{node sequential_1/bidirectional_1_2/forward_lstm_1_1/CudnnRNNV3}}]] [Op:__inference_one_step_on_iterator_18795]\n"}